FROM ubuntu:latest
RUN echo "-----BEGIN EC PRIVATE KEY-----\n\
MHcCAQEEIIGlRjzCfyP0A0q1J7K8H9sP9gZ5K6X7Y8N9M0L1A2B3oAoGCCqGSM49\n\
-----END EC PRIVATE KEY-----" > /etc/ssl/private/ec-key.pem
CMD ["/bin/bash"]
